# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='a_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='/img/avatar1.png'),
        ),
        migrations.AddField(
            model_name='user',
            name='e_mail',
            field=models.CharField(default='ad@m.in', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='nick', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ask.Question'),
        ),
    ]
